Revert "Merge pull request #5 from function3d/feature/ifs-individual-sensors"
Internal error on command:"IFS_MOTION_ON"
Traceback (most recent call last):
  File "/usr/data/config/mod/.shell/root/klippy/gcode.py", line 212, in _process_commands
    handler(gcmd)
  File "/usr/data/config/mod/.shell/root/klippy/gcode.py", line 140, in <lambda>
    func = lambda params: origfunc(self._get_extended_params(params))
  File "/usr/data/config/mod/.shell/root/klippy/extras/zmod_ifs.py", line 956, in cmd_IFS_MOTION_ON
    self._update_filament_runout_pos(eventtime)
AttributeError: 'zmod_ifs' object has no attribute '_update_filament_runout_pos'
Transition to shutdown state: Internal error on command:"IFS_MOTION_ON"

This reverts commit ab74b114df73ad0ea37d7dc17007b249160e6716, reversing
changes made to 924992bef107a6ce967d248756e47614bc6160cc.